// flow-typed signature: c6c2f09d6aeea68d92fb9e3200853664
// flow-typed version: <<STUB>>/eslint-config-bambi_v^1.4.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-bambi'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-bambi' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-bambi/__tests__/default-test' {
  declare module.exports: any;
}

declare module 'eslint-config-bambi/__tests__/fixtures/all-00' {
  declare module.exports: any;
}

declare module 'eslint-config-bambi/__tests__/fixtures/web-native-00' {
  declare module.exports: any;
}

declare module 'eslint-config-bambi/__tests__/fixtures/web-native-01' {
  declare module.exports: any;
}

declare module 'eslint-config-bambi/__tests__/fixtures/web-native-02' {
  declare module.exports: any;
}

declare module 'eslint-config-bambi/__tests__/native-test' {
  declare module.exports: any;
}

declare module 'eslint-config-bambi/__tests__/node-test' {
  declare module.exports: any;
}

declare module 'eslint-config-bambi/__tests__/tools/__lint__' {
  declare module.exports: any;
}

declare module 'eslint-config-bambi/__tests__/tools/checkPrettierRulesAsync' {
  declare module.exports: any;
}

declare module 'eslint-config-bambi/__tests__/tools/lintAsync' {
  declare module.exports: any;
}

declare module 'eslint-config-bambi/__tests__/web-test' {
  declare module.exports: any;
}

declare module 'eslint-config-bambi/default' {
  declare module.exports: any;
}

declare module 'eslint-config-bambi/native' {
  declare module.exports: any;
}

declare module 'eslint-config-bambi/node' {
  declare module.exports: any;
}

declare module 'eslint-config-bambi/shared/bamSpecific' {
  declare module.exports: any;
}

declare module 'eslint-config-bambi/shared/core' {
  declare module.exports: any;
}

declare module 'eslint-config-bambi/shared/prettier' {
  declare module.exports: any;
}

declare module 'eslint-config-bambi/shared/react' {
  declare module.exports: any;
}

declare module 'eslint-config-bambi/shared/readPrettierConfig' {
  declare module.exports: any;
}

declare module 'eslint-config-bambi/web' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-bambi/__tests__/default-test.js' {
  declare module.exports: $Exports<'eslint-config-bambi/__tests__/default-test'>;
}
declare module 'eslint-config-bambi/__tests__/fixtures/all-00.js' {
  declare module.exports: $Exports<'eslint-config-bambi/__tests__/fixtures/all-00'>;
}
declare module 'eslint-config-bambi/__tests__/fixtures/web-native-00.js' {
  declare module.exports: $Exports<'eslint-config-bambi/__tests__/fixtures/web-native-00'>;
}
declare module 'eslint-config-bambi/__tests__/fixtures/web-native-01.js' {
  declare module.exports: $Exports<'eslint-config-bambi/__tests__/fixtures/web-native-01'>;
}
declare module 'eslint-config-bambi/__tests__/fixtures/web-native-02.js' {
  declare module.exports: $Exports<'eslint-config-bambi/__tests__/fixtures/web-native-02'>;
}
declare module 'eslint-config-bambi/__tests__/native-test.js' {
  declare module.exports: $Exports<'eslint-config-bambi/__tests__/native-test'>;
}
declare module 'eslint-config-bambi/__tests__/node-test.js' {
  declare module.exports: $Exports<'eslint-config-bambi/__tests__/node-test'>;
}
declare module 'eslint-config-bambi/__tests__/tools/__lint__.js' {
  declare module.exports: $Exports<'eslint-config-bambi/__tests__/tools/__lint__'>;
}
declare module 'eslint-config-bambi/__tests__/tools/checkPrettierRulesAsync.js' {
  declare module.exports: $Exports<'eslint-config-bambi/__tests__/tools/checkPrettierRulesAsync'>;
}
declare module 'eslint-config-bambi/__tests__/tools/lintAsync.js' {
  declare module.exports: $Exports<'eslint-config-bambi/__tests__/tools/lintAsync'>;
}
declare module 'eslint-config-bambi/__tests__/web-test.js' {
  declare module.exports: $Exports<'eslint-config-bambi/__tests__/web-test'>;
}
declare module 'eslint-config-bambi/default.js' {
  declare module.exports: $Exports<'eslint-config-bambi/default'>;
}
declare module 'eslint-config-bambi/native.js' {
  declare module.exports: $Exports<'eslint-config-bambi/native'>;
}
declare module 'eslint-config-bambi/node.js' {
  declare module.exports: $Exports<'eslint-config-bambi/node'>;
}
declare module 'eslint-config-bambi/shared/bamSpecific.js' {
  declare module.exports: $Exports<'eslint-config-bambi/shared/bamSpecific'>;
}
declare module 'eslint-config-bambi/shared/core.js' {
  declare module.exports: $Exports<'eslint-config-bambi/shared/core'>;
}
declare module 'eslint-config-bambi/shared/prettier.js' {
  declare module.exports: $Exports<'eslint-config-bambi/shared/prettier'>;
}
declare module 'eslint-config-bambi/shared/react.js' {
  declare module.exports: $Exports<'eslint-config-bambi/shared/react'>;
}
declare module 'eslint-config-bambi/shared/readPrettierConfig.js' {
  declare module.exports: $Exports<'eslint-config-bambi/shared/readPrettierConfig'>;
}
declare module 'eslint-config-bambi/web.js' {
  declare module.exports: $Exports<'eslint-config-bambi/web'>;
}
